---
- name: Configure the PHP-FPM pool
  template:
    src: files/fpm-pool.conf.j2
    dest: "/etc/php/{{ php_version }}/fpm/pool.d/wudele.conf"
  notify: Restart PHP-FPM

- name: Configure the nginx site
  template:
    src: files/nginx-wudele.conf.j2
    dest: /etc/nginx/sites-available/wudele.conf
  notify: Reload nginx

- name: Enable the nginx site
  file:
    src: /etc/nginx/sites-available/wudele.conf
    dest: /etc/nginx/sites-enabled/wudele.conf
    state: link
  notify: Reload nginx

- name: Disable the default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Reload nginx

- name: Ensure the services are running
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - "php{{ php_version }}-fpm"
    - nginx
